default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/pet_alert_development

test:
  <<: *default
  database: db/pert_alert_test

production:
  <<: *default
  database: db/pery_alert_production
